name: BattleTracker

main: mc.alk.tracker.Tracker

version: 2.3.2.1

author: Alkarin
softdepend: [BattleCore,Herochat,TownyChat]
description: A tracker for PvP player related events
commands:
    battleTracker:
        aliases: [bt]
        description: Show help menu
        usage: /bt
    pvp:
        aliases: [btpvp]
        description: Show how players have matched up
        usage: /pvp player1 [player2]
    pve:
        aliases: [btpve]
        description: Show how players have matched up vs mobs/environment
        usage: /pve player1 [player2]
    
