showBukkitPVPMessages: false # turn on and off normal bukkit death messages for pvp
showBukkitPVEMessages: false # turn on and off normal bukkit death messages for pve
sendPVPDeathMessages: true # send Custom Messages on PvP deaths
sendPVEDeathMessages: true # send Custom Messages on PvE deaths

### Track Player vs Player stats
trackPvP: true

### Track Player vs Environment stats
trackPvE: false

### If showing PvP messages should we use a Herochat channel
useHeroChat: false
chatChannel: "Global" ## Which channel to use

### If number of seconds between kills is less than
### this number, show on a rampage message
rampageTime: 7

### Display a player is on a streak messages every x kills
streakMessagesEvery: 15

SQLOptions:
  type: sqlite # sqlite or mysql
  db: tracker # db name
  url : "localhost" # ignored if not mysql
  port : "3306" # ignored if not mysql
  username: "root"
  password: ""
  
## These are the default elo options, they can be overridden by calling plugins
elo:
  default: 1250
  spread: 400
